blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://eugeniodepalo.github.io/gtkx
    about: Check out our documentation for guides and API reference
  - name: Questions
    url: https://github.com/eugeniodepalo/gtkx/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
